"""Pick the example traces quoted in the supplement, and emit them verbatim.

Three examples per model, all selected mechanically so the choice cannot flatter a
model:

  sound   -- correct answer, derivation audited sound, on a DIVERGENT bin (the control
             bin is acyclic, so a sound derivation there says nothing about semantics);
  unsound -- incorrect answer whose derivation the audit contradicts.  Among the
             candidates we keep only those exhibiting the model's MODAL failure
             mechanism, so the example is the model's typical failure, not its worst;
  none    -- the untutored condition, on `even_both_sided`.  That bin is the one that
             separates a stable-model-consensus reading (definitely yes) from a
             well-founded one (cannot be determined), and we take a trace carrying the
             model's modal letter there, so the six models answer the same question
             six ways (see analyze_default_reading.py).

Within each pool the SHORTEST trace wins, so every example can be shown in full: the
supplement quotes complete traces, never elided ones, and a reader can check the
extraction against the whole text.

Emits, per example, `trace-examples/<model>-<kind>.tex` holding one fancyvrb `Verbatim`
block with the raw trace (only trailing whitespace stripped -- fancyvrb needs no
escaping, so nothing in the trace is rewritten), plus `data/trace_examples.json` with
the classification, the certified verdicts, the extracted verdicts and the matched text
span behind each one.  Paths are slugified to letters, digits and hyphens because
LaTeX's \\input chokes on an underscore in a file name.

Usage:  ./.venv/bin/python make_trace_examples.py [--outdir trace-examples] [--quiet]
"""
import argparse
import json
import os
import re
from collections import Counter

from analyze_default_reading import ORDER, READINGS
from analyze_traces import CONDS, MODELS, RUN, SET, audit_trace, certified, classify
from nafbench.answer import parse_answer_reasoning
from nafbench.instances import BIN_SIGNATURE

NONE_BIN = "even_both_sided"      # separates stable-consensus from well-founded
KINDS = ["sound", "unsound", "none"]

# The only edit made to a quoted trace: pdflatex cannot typeset these glyphs, not even
# inside Verbatim, so they are transliterated to the ASCII the model could have written.
# Anything non-ASCII that is NOT in this table aborts the run rather than shipping a
# fragment that will not compile.
TRANSLIT = {"←": "<-", "→": "->", "↔": "<->", "⇒": "=>",
            "∧": "/\\", "∨": "\\/", "¬": "~", "≠": "!=",
            "‐": "-", "‑": "-", "–": "--", "—": "---",
            "‘": "'", "’": "'", "“": '"', "”": '"',
            "…": "...", " ": " ", "≤": "<=", "≥": ">="}
HEADER = ("% Generated by make_trace_examples.py -- do not edit.\n"
          "% {tid} | {model} | cond={cond} gold={gold} answer={ans} | {verdict}\n"
          "% Complete raw output, verbatim: only trailing whitespace stripped and\n"
          "% {nsub} non-ASCII glyph(s) transliterated to ASCII ({subs}).\n")
BEGIN = (r"\begin{Verbatim}[breaklines=true,breakanywhere=true,fontsize=\scriptsize,"
         "frame=single,framesep=3pt,samepage=false]")


def slug(s):
    """LaTeX-safe file stem: \\input{} cannot take an underscore or a bare dot."""
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", s.lower())).strip("-")


def to_ascii(text, tid):
    """Transliterate the glyphs pdflatex cannot set; report what was replaced."""
    subs = Counter()
    out = []
    for ch in text:
        if ord(ch) < 128:
            out.append(ch)
            continue
        if ch not in TRANSLIT:
            raise SystemExit(f"{tid}: unmapped non-ASCII {ch!r} (U+{ord(ch):04X}); "
                             f"add it to TRANSLIT in make_trace_examples.py")
        subs[f"U+{ord(ch):04X} -> {TRANSLIT[ch]}"] += 1
        out.append(TRANSLIT[ch])
    return "".join(out), dict(subs)


def emit(path, row, text):
    if r"\end{Verbatim}" in text:
        raise SystemExit(f"{row['tid']}: trace contains a Verbatim terminator")
    body, subs = to_ascii(text.rstrip(), row["tid"])
    with open(path, "w") as fh:
        fh.write(HEADER.format(tid=row["tid"], model=row["model"], cond=row["cond"],
                               gold=row["gold"], ans=row["ans"],
                               nsub=sum(subs.values()),
                               subs=", ".join(f"{k} x{v}" for k, v in subs.items())
                               or "none",
                               verdict=row["sound"] + (f": {row['mech']}" if row["mech"]
                                                       else "")))
        fh.write(BEGIN + "\n" + body + "\n" + r"\end{Verbatim}" + "\n")
    return subs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default="trace-examples")
    ap.add_argument("--json", default="data/trace_examples.json")
    ap.add_argument("--quiet", action="store_true", help="do not print the traces")
    args = ap.parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    ev = {e["task_id"]: e for e in json.load(open(SET))}
    progs = {}
    for e in ev.values():
        progs.setdefault(e["rec_id"], e)
    cert = {rid: certified(e) for rid, e in progs.items()}

    rows, raws = [], {}
    for m in MODELS:
        raws[m] = json.load(open(f"{RUN}/{m}.raw.json"))
        for t, e in ev.items():
            txt = raws[m].get(t) or ""
            c = cert[e["rec_id"]]
            f = audit_trace(txt, c)
            ans = parse_answer_reasoning(txt, query="q")
            if e["cond"] in CONDS:
                snd, mech = classify(f, c, e["cond"], e["gold"], ans)
                req = None
            else:
                # `none` names no semantics, so there is no gold and no sound/unsound
                # verdict; what the item does carry is the letter each candidate
                # reading requires on this bin (see analyze_default_reading.py).
                snd, mech = "untutored", ""
                sig = BIN_SIGNATURE[e["divergence_bin"]]
                req = {k: READINGS[k](*sig) for k in ORDER}
            rows.append(dict(model=m, tid=t, bin=e["divergence_bin"], cond=e["cond"],
                             gold=e["gold"], ans=ans, correct=(ans == e["gold"]),
                             sound=snd, mech=mech, required=req,
                             cert_cq=c["cq"].get(e["cond"]), cert_q=c["q"].get(e["cond"]),
                             n_models=c["n_models"], **f))

    picked, skipped = [], []
    for m in MODELS:
        mine = [r for r in rows if r["model"] == m]

        # --- sound: modal condition among the model's sound divergent-bin traces
        pool = [r for r in mine if r["cond"] in CONDS and r["correct"]
                and r["sound"] == "sound" and r["bin"] != "control"]
        if pool:
            modal = Counter(r["cond"] for r in pool).most_common(1)[0][0]
            best = min([r for r in pool if r["cond"] == modal], key=lambda r: r["chars"])
            picked.append(("sound", best, f"modal condition {modal}, "
                                          f"{len(pool)} candidates"))
        else:
            skipped.append((m, "sound"))

        # --- unsound: modal failure mechanism among wrong answers
        pool = [r for r in mine if r["cond"] in CONDS and not r["correct"]
                and r["sound"] == "unsound"]
        if pool:
            modal = Counter(r["mech"] for r in pool).most_common(1)[0][0]
            best = min([r for r in pool if r["mech"] == modal], key=lambda r: r["chars"])
            picked.append(("unsound", best, f"modal mechanism \"{modal}\", "
                                            f"{len(pool)} candidates"))
        else:
            skipped.append((m, "unsound"))

        # --- none: modal letter on the identifying bin
        pool = [r for r in mine if r["cond"] == "none" and r["bin"] == NONE_BIN]
        modal = Counter(r["ans"] for r in pool).most_common(1)[0][0]
        best = min([r for r in pool if r["ans"] == modal], key=lambda r: r["chars"])
        picked.append(("none", best, f"modal letter {modal} on {NONE_BIN} "
                                     f"({sum(1 for r in pool if r['ans'] == modal)}"
                                     f"/{len(pool)})"))

    out = []
    for kind, r, why in picked:
        path = os.path.join(args.outdir, f"{slug(r['model'])}-{kind}.tex")
        subs = emit(path, r, raws[r["model"]][r["tid"]])
        rec = dict(kind=kind, path=path, selection=why, translit=subs,
                   **{k: r[k] for k in ("model", "tid", "bin", "cond", "gold", "ans",
                                        "correct", "sound", "mech", "required", "chars",
                                        "cert_cq", "cert_q", "n_models", "cycle_seen",
                                        "no_models", "multi_models", "cq_said", "cq_span",
                                        "q_said", "q_span")})
        out.append(rec)
        print(f"{path}  ({r['chars']} chars, {sum(subs.values())} transliterated)  [{why}]")
    for m, kind in skipped:
        print(f"-- {m}: no {kind} example exists "
              f"({'no incorrect answer in 480 scored prompts' if kind == 'unsound' else 'none'})")

    json.dump(out, open(args.json, "w"), indent=1)
    print(f"\nselection records -> {args.json}")

    if not args.quiet:
        for rec in out:
            print("\n" + "=" * 78)
            print(f"{rec['model']} | {rec['tid']} | kind={rec['kind']} "
                  f"bin={rec['bin']} cond={rec['cond']}")
            print(f"gold={rec['gold']} answer={rec['ans']} -> {rec['sound']}"
                  + (f": {rec['mech']}" if rec["mech"] else ""))
            print(f"certified cq={rec['cert_cq']} q={rec['cert_q']} "
                  f"stable models={rec['n_models']}")
            print(f"trace says cq={rec['cq_said']!r} q={rec['q_said']!r} | "
                  f"cycle_seen={rec['cycle_seen']} no_models={rec['no_models']} "
                  f"multi_models={rec['multi_models']}")
            print(f"cq span « {rec['cq_span']} »")
            print(f"q  span « {rec['q_span']} »")
            print("-" * 78)
            print(raws[rec["model"]][rec["tid"]].rstrip())


if __name__ == "__main__":
    main()
